name: build
on: pull_request #changed this
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps: 
      - name: my first step
        env:
          MY_VAR: Hi there! my name is
          FIRST_NAME: Mayank
          LAST_NAME: Sharma
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
      - name: my second step
        if: success()
        run: echo "The previous step has finished successfully"
      - name: my third step
        uses: actions/checkout@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com/ # if your publishing your package to npm or github package repo
      - name: my fourth step
        uses: actions/setup-node@v1
      - name: my fifth step
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Message that will be displayed on users first issue'
          pr-message: 'message that will be displayed on users first pr' 

          
          
