---
name: Build & pull request

on:
  push:
    branches: [development-server]

jobs:  
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: testing if it works
      run: echo building ....



  staging-pull-request:
    runs-on: ubuntu-latest
    name: staging-pull-request
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: staging-server
      env:
        BUILD_TOKEN: ${{ secrets.BUILD_TOKEN }}
        DRY_RUN: false

