name: build
on: push
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps: 
      - name: my first step
        env:
          MY_VAR: Hi there! my name is
          FIRST_NAME: Mayank
          LAST_NAME: Sharma
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
      - name: my second job
        if: success()
        run: echo "The previous step has finished successfully"
        
          
          
